version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: utsav
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5439:5439"

  redis:
    image: redis:latest
    ports:
      - "6380:6380"

  rabbitmq:
    image: rabbitmq:latest
    ports:
      - "5675:5675"
      - "15673:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
